language: python
python:
  - "2.7"

before_install:
  - cd ..
  # Install miniconda
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then wget http://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then wget http://repo.continuum.io/miniconda/Miniconda2-latest-MacOSX-x86_64.sh -O miniconda.sh; fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH=$HOME/miniconda/bin:$PATH
  # Update conda
  - conda update --yes conda
  - conda info -a
  # Set git info
  - git config --global user.name "Travis Deploy"
  - git config --global user.email "alongd@mit.edu"

cache: pip
install:
  - cd ARC
  - pip install -r requirements.txt
  - conda install -y -c rmg rmg
  - conda install -y -c rdkit rdkit

script:
  make test
