name: arc_env
channels:
  - defaults
  - rmg
  - anaconda
  - omnia
  - conda-forge
dependencies:
  - cairo
  - cairocffi
  - rmg::cantera >=2.3.0
  - cclib >=1.6
  - rmg::chemprop
  - codecov
  - coolprop
  - coverage
  - cython >=0.25.2
  - ffmpeg
  - rmg::gprof2dot
  - graphviz
  - h5py
  - jinja2
  - jupyter
  - rmg::lpsolve55
  - markupsafe
  - matplotlib >=2.2.2
  - mock
  - rmg::mopac
  - mpmath
  - networkx
  - nose
  - rmg::numdifftools
  - numpy >=1.15.4
  - openbabel
  - pandas >=1.0.1
  - psutil
  - rmg::pydas >=1.0.2
  - pydot
  - rmg::pydqed >=1.0.1
  - pymongo
  - pyparsing
  - rmg::pyrdl
  - python >=3.7
  - pyyaml
  - rmg::quantities
  - rmg::rdkit >=2020.03.3.0
  - scikit-learn
  - scipy
  - sphinx_rtd_theme
  - rmg::symmetry
  - xlwt
  - paramiko >=2.6.0
  - py3dmol >= 0.8.0
  - ase >=3.15.0
  - ipython
  - sphinx
  - qcelemental
