name: tani_env
channels:
  - anaconda
  - defaults
  - pytorch
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - aiofiles=22.1.0
  - aiosqlite=0.18.0
  - alsa-lib=1.2.3.2
  - anyio=3.6.2
  - aom=3.5.0
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - ase=3.22.1
  - asttokens=2.2.1
  - atk-1.0=2.38.0
  - attrs=22.2.0
  - babel=2.12.1
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.4
  - bcrypt=3.2.2
  - beautifulsoup4=4.11.2
  - biopython=1.81
  - blas=2.116
  - blas-devel=3.9.0
  - bleach=6.0.0
  - bottleneck=1.3.7
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - ca-certificates=2022.12.7
  - cairo=1.16.0
  - cclib=1.7.2
  - certifi=2022.12.7
  - cffi=1.15.1
  - charset-normalizer=2.1.1
  - click=8.1.3
  - comm=0.1.2
  - contourpy=1.0.7
  - cpuonly=2.0
  - cryptography=39.0.0
  - cycler=0.11.0
  - dbus=1.13.6
  - debugpy=1.6.6
  - decorator=5.1.1
  - defusedxml=0.7.1
  - entrypoints=0.4
  - executing=1.2.0
  - expat=2.5.0
  - ffmpeg=5.1.2
  - flask=2.2.3
  - flit-core=3.8.0
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.2
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.39.0
  - freetype=2.12.1
  - fribidi=1.0.10
  - gdk-pixbuf=2.42.10
  - gettext=0.21.1
  - glib=2.74.1
  - glib-tools=2.74.1
  - gmp=6.2.1
  - gnutls=3.7.8
  - graphite2=1.3.13
  - graphviz=4.0.0
  - gst-plugins-base=1.20.2
  - gstreamer=1.20.3
  - gtk2=2.24.33
  - gts=0.7.6
  - harfbuzz=4.2.0
  - icu=69.1
  - idna=3.4
  - importlib-metadata=6.0.0
  - importlib_metadata=6.0.0
  - importlib_resources=5.12.0
  - ipykernel=6.21.3
  - ipython=8.11.0
  - ipython_genutils=0.2.0
  - ipywidgets=8.0.4
  - itsdangerous=2.1.2
  - jedi=0.18.2
  - jinja2=3.1.2
  - joblib=1.2.0
  - jpeg=9e
  - json5=0.9.5
  - jsonschema=4.17.3
  - jupyter=1.0.0
  - jupyter_client=8.0.3
  - jupyter_console=6.6.3
  - jupyter_core=5.2.0
  - jupyter_events=0.6.3
  - jupyter_server=2.4.0
  - jupyter_server_fileid=0.8.0
  - jupyter_server_terminals=0.4.4
  - jupyter_server_ydoc=0.6.1
  - jupyter_ydoc=0.2.2
  - jupyterlab=3.6.1
  - jupyterlab_pygments=0.2.2
  - jupyterlab_server=2.20.0
  - jupyterlab_widgets=3.0.5
  - keyutils=1.6.1
  - kiwisolver=1.4.4
  - krb5=1.20.1
  - lame=3.100
  - lark-parser=0.12.0
  - lcms2=2.15
  - ld_impl_linux-64=2.40
  - lerc=4.0.0
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcblas=3.9.0
  - libclang=13.0.1
  - libdeflate=1.17
  - libdrm=2.4.114
  - libedit=3.1.20191231
  - libevent=2.1.10
  - libffi=3.4.2
  - libgcc-ng=12.2.0
  - libgd=2.3.3
  - libgfortran-ng=12.2.0
  - libgfortran5=12.2.0
  - libglib=2.74.1
  - libhwloc=2.8.0
  - libiconv=1.17
  - libidn2=2.3.4
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - libllvm13=13.0.1
  - libnsl=2.0.0
  - libogg=1.3.4
  - libopus=1.3.1
  - libpciaccess=0.17
  - libpng=1.6.39
  - libpq=14.5
  - librsvg=2.54.4
  - libsodium=1.0.18
  - libsqlite=3.40.0
  - libstdcxx-ng=12.2.0
  - libtasn1=4.19.0
  - libtiff=4.5.0
  - libtool=2.4.7
  - libunistring=0.9.10
  - libuuid=2.32.1
  - libva=2.17.0
  - libvorbis=1.3.7
  - libvpx=1.11.0
  - libwebp-base=1.3.0
  - libxcb=1.13
  - libxkbcommon=1.0.3
  - libxml2=2.9.14
  - libzlib=1.2.13
  - llvm-openmp=15.0.7
  - markupsafe=2.1.2
  - matplotlib=3.7.1
  - matplotlib-base=3.7.1
  - matplotlib-inline=0.1.6
  - mistune=2.0.5
  - mkl=2022.1.0
  - mkl-devel=2022.1.0
  - mkl-include=2022.1.0
  - munkres=1.1.4
  - mysql-common=8.0.32
  - mysql-libs=8.0.32
  - nbclassic=0.5.3
  - nbclient=0.7.2
  - nbconvert=7.2.9
  - nbconvert-core=7.2.9
  - nbconvert-pandoc=7.2.9
  - nbformat=5.7.3
  - ncurses=6.3
  - nest-asyncio=1.5.6
  - nettle=3.8.1
  - networkx=3.0
  - nomkl=2.0
  - notebook=6.5.3
  - notebook-shim=0.2.2
  - nspr=4.35
  - nss=3.82
  - numexpr=2.8.3
  - numpy=1.24.2
  - openh264=2.3.1
  - openjpeg=2.5.0
  - openssl=1.1.1t
  - p11-kit=0.24.1
  - packaging=23.0
  - pandas=1.5.3
  - pandoc=2.19.2
  - pandocfilters=1.5.0
  - pango=1.50.7
  - paramiko=3.0.0
  - parso=0.8.3
  - pcre2=10.40
  - periodictable=1.5.2
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=9.4.0
  - pip=23.0.1
  - pixman=0.40.0
  - pkgutil-resolve-name=1.3.10
  - platformdirs=3.1.1
  - pooch=1.7.0
  - prometheus_client=0.16.0
  - prompt-toolkit=3.0.38
  - prompt_toolkit=3.0.38
  - psutil=5.9.4
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - py3dmol=2.0.1.post1
  - pycparser=2.21
  - pygments=2.14.0
  - pynacl=1.5.0
  - pyopenssl=23.0.0
  - pyparsing=3.0.9
  - pyqt=5.12.3
  - pyqt-impl=5.12.3
  - pyqt5-sip=4.19.18
  - pyqtchart=5.12
  - pyqtwebengine=5.12.1
  - pyrsistent=0.19.3
  - pysocks=1.7.1
  - python=3.10.8
  - python-dateutil=2.8.2
  - python-fastjsonschema=2.16.3
  - python-json-logger=2.0.7
  - python_abi=3.10
  - pytorch=1.13.1
  - pytorch-mutex=1.0
  - pytz=2022.7.1
  - pyyaml=6.0
  - pyzmq=25.0.0
  - qt=5.12.9
  - qtconsole=5.4.1
  - qtconsole-base=5.4.1
  - qtpy=2.3.0
  - readline=8.1.2
  - requests=2.28.2
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - scikit-learn=1.2.2
  - scipy=1.10.1
  - send2trash=1.8.0
  - setuptools=67.6.0
  - six=1.16.0
  - sniffio=1.3.0
  - soupsieve=2.3.2.post1
  - sqlite=3.40.0
  - stack_data=0.6.2
  - svt-av1=1.3.0
  - tbb=2021.7.0
  - terminado=0.17.1
  - threadpoolctl=3.1.0
  - tinycss2=1.2.1
  - tk=8.6.12
  - tomli=2.0.1
  - torchani=2.2
  - torchaudio=0.13.1
  - torchvision=0.14.1
  - tornado=6.2
  - traitlets=5.9.0
  - typing-extensions=4.5.0
  - typing_extensions=4.5.0
  - tzdata=2022g
  - unicodedata2=15.0.0
  - urllib3=1.26.15
  - wcwidth=0.2.6
  - webencodings=0.5.1
  - websocket-client=1.5.1
  - werkzeug=2.2.3
  - wheel=0.40.0
  - widgetsnbextension=4.0.5
  - x264=1!164.3095
  - x265=3.5
  - xorg-fixesproto=5.0
  - xorg-kbproto=1.0.7
  - xorg-libice=1.0.10
  - xorg-libsm=1.2.3
  - xorg-libx11=1.8.4
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.4
  - xorg-libxfixes=5.0.3
  - xorg-libxrender=0.9.10
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.2.6
  - y-py=0.5.9
  - yaml=0.2.5
  - ypy-websocket=0.8.2
  - zeromq=4.3.4
  - zipp=3.15.0
  - zlib=1.2.13
  - zstd=1.5.2
