name: Docker Image Build and Push

on:
  schedule:
    - cron: "0 0 */7 * *" # every 7 days
  push:
    branches:
        - main
  pull_request:
    branches:
        - main
    paths:
        - './Dockerfile'
jobs:
  ci-check:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build ARC
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: false
  
  build-and-push:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Build and push ARC
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/arc:latest
        