name: github pages

on:
  push:
    branches:
      - main
      - docs

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}

    steps:
    - uses: actions/checkout@v3

    - name: Clean Ubuntu Image
      uses: kfir4444/free-disk-space@main
      with:
        # This may remove tools actually needed - currently does not
        tool-cache: true
        android: true
        dotnet: true
        haskell: true
        large-packages: true
        swap-storage: true

      run: |
        mamba env update -n arc_env -f environment.yml
        conda list

    - name: Install LaTeX
      run: |
        sudo apt update -y && sudo apt upgrade -y && sudo apt autoremove -y
        sudo apt install texlive-latex-base -y
        sudo apt-get install texlive-latex-extra -y
        sudo apt-get install -y dvipng


    - name: Install codecov
      run: conda install --force-reinstall ld_impl_linux-64 -y && conda install -y -c conda-forge codecov

    - name: Install dependencies
      run: |
        export PYTHONPATH=$PYTHONPATH:$(pwd)
        conda activate arc_env
        cd ..
        git clone https://github.com/ReactionMechanismGenerator/RMG-database
        git clone https://github.com/ReactionMechanismGenerator/RMG-Py
        cd RMG-Py
        export PYTHONPATH=$PYTHONPATH:$(pwd)
        make
        cd ../ARC/
        conda deactivate

    - name: Compile docs
      run: |
        export PYTHONPATH=$PYTHONPATH:$(pwd)
        conda activate arc_env
        cd ../RMG-Py
        export PYTHONPATH=$PYTHONPATH:$(pwd)
        cd ../ARC/docs/
        make html

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3.7.3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs/build/html/

# https://github.com/marketplace/actions/github-pages-action
