name: github pages

on:
  push:
    branches:
      - master
      - docs

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up miniconda Python 3.8
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: arc_env
          environment-file: environment.yml
          python-version: 3.8
          auto-activate-base: false

      - name: Install dependencies and compile the docs
        shell: bash -l {0}
        run: |
          export PYTHONPATH=$PYTHONPATH:$(pwd)
          conda activate arc_env
          cd ..
          git clone https://github.com/ReactionMechanismGenerator/RMG-Py
          cd RMG-Py
          export PYTHONPATH=$PYTHONPATH:$(pwd)
          make
          cd ..
          git clone https://github.com/ReactionMechanismGenerator/RMG-database
          cd ARC
          echo $(pwd)
          conda list

      - name: Compile docs
        shell: bash -l {0}
        run: |
          export PYTHONPATH=$PYTHONPATH:$(pwd)
          conda activate arc_env
          cd ..
          cd RMG-Py
          export PYTHONPATH=$PYTHONPATH:$(pwd)
          cd ..
          cd ARC
          cd docs
          make html

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3.7.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/build/html/

# https://github.com/marketplace/actions/github-pages-action
